/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Controladores.AdjudicacionControlador;
import Controladores.PedidoControlador;
import Entidades.Adjudicacion;
import Entidades.Pedido;
import Metodos.Adjudicaciones;
import Metodos.Ofertas;
import Metodos.Pedidos;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ProcesosE
 */
public final class adjudicaciones extends javax.swing.JFrame {

    DefaultTableModel modelo;
    private int idPedido;
    private int idOferta;
    private int montoAdjudicacion;
    private String tipoAdjudicacion;
    
    /**
     * Creates new form adjudicaciones
     */
    public adjudicaciones() {
        initComponents();
        
        modelo = new DefaultTableModel();
        modelo.addColumn("ID ADJUDICACION");
        modelo.addColumn("ID OFERTA");
        modelo.addColumn("MONTO ADJUDICACION");
        modelo.addColumn("TIPO ADJUDICACION");
        modelo.addColumn("FECHA ADJUDICACION");
        modelo.addColumn("USUARIO QUE ADJUDICO");
        
        this.TablaAdjudicacion.setModel(modelo);
        
        mostrarAdjudicaciones();
        
            this.setLocationRelativeTo(null);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAdjudicacion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        bt_crearorden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TablaAdjudicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaAdjudicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAdjudicacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaAdjudicacion);

        jLabel1.setText("ADJUDICACION");

        bt_crearorden.setText("CREAR ORDEN DE COMPRA");
        bt_crearorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearordenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(bt_crearorden)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_crearorden)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crearordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearordenActionPerformed
        // TODO add your handling code here:
        
        orden_compra f1 = new orden_compra(idPedido,idOferta,montoAdjudicacion,tipoAdjudicacion);
                f1.setVisible(true);
                setVisible(false);
        
        
        
    }//GEN-LAST:event_bt_crearordenActionPerformed

    private void TablaAdjudicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAdjudicacionMouseClicked
        // TODO add your handling code here:
        
         int selectedRow = TablaAdjudicacion.getSelectedRow();
                    if (selectedRow != -1) {
                        // Obtiene los datos de la fila seleccionada
                        idPedido = (int) TablaAdjudicacion.getValueAt(selectedRow, 0);
                        idOferta = (int) TablaAdjudicacion.getValueAt(selectedRow, 1);
                        montoAdjudicacion = (int) TablaAdjudicacion.getValueAt(selectedRow, 2);
                        tipoAdjudicacion = (String) TablaAdjudicacion.getValueAt(selectedRow, 3);
                        Date fecha = (Date) TablaAdjudicacion.getValueAt(selectedRow, 4);
                        String usuario = (String) TablaAdjudicacion.getValueAt(selectedRow, 5);
                        
                        Adjudicacion nuevaAdjudicacion = AdjudicacionControlador.adjudicacionVista(idPedido, idOferta, montoAdjudicacion,tipoAdjudicacion,fecha,usuario);
                        
                       // Pedido nuevoPedido = PedidoControlador.pedidoVista(idPedido, descripcion);
                        
                        
                        // Muestra los datos en el JTextField
                        System.out.println("Columna 1: " + idPedido + ", Columna 2: " + idOferta+ "Columna 3: " + montoAdjudicacion + ", Columna 4: " + tipoAdjudicacion+fecha+usuario);
//                        textField.setText("Columna 1: " + data1 + ", Columna 2: " + data2);
                    }
    }//GEN-LAST:event_TablaAdjudicacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adjudicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adjudicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adjudicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adjudicaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adjudicaciones().setVisible(true);
            }
        });
    }
    
    public void mostrarAdjudicaciones(){
        Adjudicaciones ad = new Adjudicaciones();
        
       ArrayList<Adjudicacion> datosAdjudicacion  = ad.obtenerAdjudicaciones();
//        ComboTipoProducto.addItem("Seleccionar");
        
        for (Adjudicacion adjudicacion : datosAdjudicacion) {
            Object[] fila = {
                
                    adjudicacion.getID_ADJUDICACION(),
                    adjudicacion.getID_OFERTA(),
                    adjudicacion.getMONTO_ADJUDICACION(),
                    adjudicacion.getTIPO_ADJUDICACION(),
                    adjudicacion.getFECHA_ADJUDICACION(),
                    adjudicacion.getUSUARIO_ADJUDICA()
                    
            };
            modelo.addRow(fila);
        }
    
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaAdjudicacion;
    private javax.swing.JButton bt_crearorden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
