/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Controladores.OfertaControlador;
import Controladores.PedidoControlador;
import Entidades.Departamento;
import Entidades.Oferta;
import Entidades.OfertaDetalle;
import Entidades.Pedido;
import Entidades.PedidoDetalle;
import Entidades.Proveedor;
import Entidades.Proveedor1;
import Metodos.Pedidos;
import Metodos.Proveedores;
import Procesos_Almacenados.SPOferta;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ProcesosE
 */
public final class ofertas extends javax.swing.JFrame {

    DefaultTableModel modelo;
    DefaultTableModel modeluky;
    
//    private final int idPedido;
//    private final String descripcion;

    /**
     * Creates new form ofertas
     * @param idPedido
     * @param descripcion
     */
    public ofertas(int idPedido, String descripcion) {
        initComponents();
        MostrarProveedores();
        
        txt_idpedido.setText(String.valueOf(idPedido));
        txt_descripcionpedido.setText(descripcion);
        txt_idpedido.setEditable(false);
        txt_descripcionpedido.setEditable(false);
        txt_nombreproducto.setEditable(false);
        txt_descripcionproducto.setEditable(false);
        txt_cantidad.setEditable(false);
        txt_idproducto.setEditable(false);
        
        modelo = new DefaultTableModel();
        modelo.addColumn("NOMBRE DEL PRODUCTO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("CANTIDAD SOLICITADA");
        modelo.addColumn("ID PRODUCTO");
        modelo.addColumn("ID PEDIDO");
        modelo.addColumn("ID PEDIDO DETALLE");
        
        this.TablaPedidoDetalle.setModel(modelo);
        int idPedidoDetalle = Integer.parseInt(txt_idpedido.getText());
        
        MostrarDatosTabla(idPedidoDetalle);
        
        modeluky = new DefaultTableModel();
        modeluky.addColumn("NOMBRE DEL PRODUCTO");
        modeluky.addColumn("DESCRIPCION");
        modeluky.addColumn("CANTIDAD");
        modeluky.addColumn("ID PRODUCTO");
        modeluky.addColumn("PRECIO UNITARIO");
        modeluky.addColumn("PRECIO");
        
        this.TablaAgregarOferta.setModel(modeluky);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_idpedido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_descripcionpedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Combonombreproveedor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Comboidproveedor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPedidoDetalle = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_idproducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nombreproducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_descripcionproducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_precioporunidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_preciototal = new javax.swing.JTextField();
        bt_agregar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaAgregarOferta = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bt_enviaroferta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txt_idpedido.setBackground(new java.awt.Color(255, 255, 255));
        txt_idpedido.setBorder(null);

        jLabel1.setText("ID_PEDIDO");

        txt_descripcionpedido.setBackground(new java.awt.Color(255, 255, 255));
        txt_descripcionpedido.setBorder(null);

        jLabel2.setText("DESCRIPCION");

        jLabel4.setText("NOMBRE DEL PROVEEDOR");

        Comboidproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboidproveedorActionPerformed(evt);
            }
        });

        jLabel3.setText("ID_PROVEEDOR");

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setBorder(null);

        jLabel5.setText("VIGENCIA DE OFERTA");

        TablaPedidoDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaPedidoDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPedidoDetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPedidoDetalle);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel6.setText("ID PRODUCTO");

        txt_idproducto.setBackground(new java.awt.Color(255, 255, 255));
        txt_idproducto.setBorder(null);

        jLabel7.setText("NOMBRE PRODUCTO");

        txt_nombreproducto.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombreproducto.setBorder(null);

        jLabel8.setText("DESCRIPCION");

        txt_descripcionproducto.setBackground(new java.awt.Color(255, 255, 255));
        txt_descripcionproducto.setBorder(null);

        jLabel9.setText("CANTIDAD");

        txt_cantidad.setBackground(new java.awt.Color(255, 255, 255));
        txt_cantidad.setBorder(null);

        jLabel10.setText("PRECIO POR UNIDAD");

        txt_precioporunidad.setBackground(new java.awt.Color(255, 255, 255));
        txt_precioporunidad.setBorder(null);
        txt_precioporunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioporunidadActionPerformed(evt);
            }
        });

        jLabel11.setText("PRECIO TOTAL");

        txt_preciototal.setBackground(new java.awt.Color(255, 255, 255));
        txt_preciototal.setBorder(null);

        bt_agregar.setText("AGREGAR");
        bt_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(bt_agregar)
                                .addGap(22, 22, 22))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_idproducto)
                            .addComponent(txt_descripcionproducto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_precioporunidad, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_cantidad)
                                            .addComponent(txt_preciototal))
                                        .addGap(10, 10, 10))
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_idproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txt_descripcionproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_preciototal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(txt_precioporunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_agregar)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablaAgregarOferta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaAgregarOferta);

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));

        bt_enviaroferta.setText("ENVIAR OFERTA");
        bt_enviaroferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarofertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_enviaroferta)
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(bt_enviaroferta)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("OFERTAS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2))
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(Comboidproveedor, 0, 171, Short.MAX_VALUE)
                    .addComponent(txt_idpedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(txt_descripcionpedido)
                    .addComponent(Combonombreproveedor, 0, 203, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_descripcionpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comboidproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(Combonombreproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboidproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboidproveedorActionPerformed
        // TODO add your handling code here:
        String idSeleccionado = (String) Comboidproveedor.getSelectedItem();
        if (!idSeleccionado.equals("Seleccionar")) {
            
            int idProveedor = Integer.parseInt(idSeleccionado);
            
            actualizarCombonombreproveedor(idProveedor);
        }
        
    }//GEN-LAST:event_ComboidproveedorActionPerformed

    private void TablaPedidoDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPedidoDetalleMouseClicked
        // TODO add your handling code here:
        
        int selectedRow = TablaPedidoDetalle.getSelectedRow();
                    if (selectedRow != -1) {
                        // Obtiene los datos de la fila seleccionada
                        String nom = (String) TablaPedidoDetalle.getValueAt(selectedRow, 0);
                        String des = (String) TablaPedidoDetalle.getValueAt(selectedRow, 1);
                        int can = (int) TablaPedidoDetalle.getValueAt(selectedRow, 2);
                        int idprod = (int) TablaPedidoDetalle.getValueAt(selectedRow, 3);
                        int idped = (int) TablaPedidoDetalle.getValueAt(selectedRow, 4);
                        int idpedde = (int) TablaPedidoDetalle.getValueAt(selectedRow, 5);
                        
                        String cantx = String.valueOf(can);
                        String idprodtx = String.valueOf(idprod);
                        
                        txt_nombreproducto.setText(nom);
                        txt_descripcionproducto.setText(des);
                        txt_cantidad.setText(cantx);
                        txt_idproducto.setText(idprodtx);
//                        
//                        int preuni = Integer.parseInt(txt_precioporunidad.getText());
//                        int pretot = preuni * can;
//                        String pretotxt = String.valueOf(pretot);
                        //txt_preciototal.setText(pretotxt);
                        
                        System.out.println(nom + des + can + idprod + idped+ idpedde+cantx+idprodtx);
                        
//                        InsertarTabla(nom, des, can, idprod, preuni, pretot);
//                        
//                        Pedido nuevoPedido = PedidoControlador.pedidoVista(idPedido, descripcion);
                        
                        
                        // Muestra los datos en el JTextField
//                        System.out.println("Columna 1: " + idPedido + ", Columna 2: " + descripcion+ "Columna 3: " + data3 + ", Columna 4: " + data4);
//                        textField.setText("Columna 1: " + data1 + ", Columna 2: " + data2);
                    }
                    
    }//GEN-LAST:event_TablaPedidoDetalleMouseClicked

    private void bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarActionPerformed
        // TODO add your handling code here:
        int idp = Integer.parseInt(txt_idproducto.getText());
        String nomp = txt_nombreproducto.getText();
        String descr = txt_descripcionproducto.getText();
        int canti = Integer.parseInt(txt_cantidad.getText());
        
        int preuni = Integer.parseInt(txt_precioporunidad.getText());
        int pretot = preuni * canti;
        String pretotxt = String.valueOf(pretot);
        txt_preciototal.setText(pretotxt);
        
        
                        InsertarTabla(nomp, descr, canti, idp, preuni, pretot);
        
        
        
        
        
    }//GEN-LAST:event_bt_agregarActionPerformed

    private void bt_enviarofertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarofertaActionPerformed
        // TODO add your handling code here:
        
        String idProveedorSeleccionado = (String) Comboidproveedor.getSelectedItem();
        String NombreSeleccionado = (String) Combonombreproveedor.getSelectedItem();
        
        if (!idProveedorSeleccionado.equals("Seleccionar")) {
            if (!NombreSeleccionado.equals("Seleccionar")) {
                
               int idpedido = Integer.parseInt(txt_idpedido.getText());
               int idproveedor = Integer.parseInt(idProveedorSeleccionado);
               
               Oferta nuevaoferta = OfertaControlador.insertarOfertaEncabezado(idproveedor, idpedido, NombreSeleccionado);
               
               SPOferta.agregarOfertaEncabezado(nuevaoferta);
               
               TablaAgregarOferta.getModel();
            
            for (int i = 0; i < modeluky.getRowCount(); i++) {
            
            String NOMBRE_PRODUCTO = (String) modeluky.getValueAt(i, 0); 
            String DESCRIPCION = (String) modeluky.getValueAt(i, 1); 
            int CANTIDAD = (int) modeluky.getValueAt(i, 2);
            int ID_PRODUCTO = (int) modeluky.getValueAt(i, 3);
            int PRECIO_UNITARIO = (int) modeluky.getValueAt(i, 4); // Suponiendo que la columna 2 contiene la DESCRIPCION_PRODUCTO
            int PRECIO = (int) modeluky.getValueAt(i, 5); // Suponiendo que la columna 3 contiene la CANTIDAD_SOLICITADA
            
            
            OfertaDetalle nuevaOfertaDetalle = OfertaControlador.insertarOfertaDetalle(ID_PRODUCTO, NOMBRE_PRODUCTO, DESCRIPCION, CANTIDAD, PRECIO, PRECIO_UNITARIO);
            
            SPOferta.agregarOfertaDetalle(nuevaOfertaDetalle);
            
            }
            
        }
            
            
        }
        
        
    }//GEN-LAST:event_bt_enviarofertaActionPerformed

    private void txt_precioporunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioporunidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioporunidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ofertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ofertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ofertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ofertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ofertas(int idPedido, String descripcion).setVisible(true);
            }
        });
    }
    
    public void MostrarProveedores(){
        Proveedores prov = new Proveedores();
        
        ArrayList<Proveedor1> datosProveedor = prov.obtenerProveedor();
        Comboidproveedor.addItem("Seleccionar");
        
        for (int i = 0; i < datosProveedor.size(); i++){
            Comboidproveedor.addItem(String.valueOf(datosProveedor.get(i).getID_PROVEEDOR()));
        }
    
    }
    
    public void actualizarCombonombreproveedor(int idProveedor){
    
        Combonombreproveedor.removeAllItems(); // Limpiar el combo antes de actualizar
    
    Proveedores prov = new Proveedores();
    ArrayList<Proveedor1> nombreproveedor = prov.obtenerNombreProveedor(idProveedor);
    
    for (Proveedor1 proveedor : nombreproveedor) {
        Combonombreproveedor.addItem(proveedor.getNOMBRE_PROVEEDOR());
    }
    }
    
    public void MostrarDatosTabla(int idPedidoDetalle){
    
        Pedidos ped = new Pedidos();
        
       ArrayList<PedidoDetalle> datosPedidoDetalle  = ped.obtenerPedidoDetalle(idPedidoDetalle);
//        ComboTipoProducto.addItem("Seleccionar");
        
        for (PedidoDetalle pedidodetalle : datosPedidoDetalle) {
            Object[] fila = {
                
                    pedidodetalle.getNOMBRE_PRODUCTO(),
                    pedidodetalle.getDESCRIPCION_PRODUCTO(),
                    pedidodetalle.getCANTIDAD_SOLICITADA(),
                    pedidodetalle.getID_PRODUCTO(),
                    pedidodetalle.getID_PEDIDO(),
                    pedidodetalle.getID_PEDIDO_DETALLE()
                    
            };
            modelo.addRow(fila);
        }
    
    }
    
    public void InsertarTabla(String nomp, String descr, int canti, int idp, int preuni, int pretot){
        
        
        
    Object[] fila = {nomp, descr, canti, idp, preuni, pretot};
        modeluky.addRow(fila);
    
    }
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Comboidproveedor;
    private javax.swing.JComboBox<String> Combonombreproveedor;
    private javax.swing.JTable TablaAgregarOferta;
    private javax.swing.JTable TablaPedidoDetalle;
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_enviaroferta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcionpedido;
    private javax.swing.JTextField txt_descripcionproducto;
    private javax.swing.JTextField txt_idpedido;
    private javax.swing.JTextField txt_idproducto;
    private javax.swing.JTextField txt_nombreproducto;
    private javax.swing.JTextField txt_precioporunidad;
    private javax.swing.JTextField txt_preciototal;
    // End of variables declaration//GEN-END:variables
}
